meses_anio=["ENERO",
            "FEBRERO",
            "MARZ0",
            "ABRIL",
            "MAYO",
            "JUNIO",
            "JULIO",
            "AGOSTO",
            "SEPTIEMBRE",
            "OCTUBRE",
            "NOVIEMBRE",
            "DICIEMBRE"]
meses_anio[10]="PREDICIEMBRE"
meses_anio.append("POSDICIEMBRE")
print(meses_anio)